version: '3'

services:
  app_demo:
    build: API_REST
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://java_db:5432/crud?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: postgres
      DB_PASSWORD: admin1234
    restart: always
    depends_on:
      java_db:
        condition: service_healthy

  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

